# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:56
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_up_RichField',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='带图片上传功能的富文本编辑器')),
            ],
        ),
        migrations.CreateModel(
            name='None_Image_up_RichField',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Body', ckeditor.fields.RichTextField(verbose_name='普通富文本编辑器')),
            ],
        ),
    ]
